


-- PRODUTOR_ESTRADA
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '64663646068', NULL, 'Carlos Menezes', '1985-03-12', 'PRODUTOR_ESTRADA', NULL),
(TRUE, '23840363033', NULL, 'Fernanda Rocha', '1990-07-25', 'PRODUTOR_ESTRADA', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'carlos.menezes@email.com', 'carlosmenezes', '$2a$10$senhaHash1', 1),
(NULL, NULL, CURRENT_TIMESTAMP, 'fernanda.rocha@email.com', 'fernandarocha', '$2a$10$senhaHash2', 2);

-- PRE_PRODUTOR
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '53987542082', NULL, 'João Almeida', '1988-11-02', 'PRE_PRODUTOR', NULL),
(TRUE, '05356247009', NULL, 'Mariana Silva', '1992-04-18', 'PRE_PRODUTOR', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'joao.almeida@email.com', 'joaoalmeida', '$2a$10$senhaHash3', 3),
(NULL, NULL, CURRENT_TIMESTAMP, 'mariana.silva@email.com', 'marianasilva', '$2a$10$senhaHash4', 4);

-- PRODUTOR
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '70686235007', NULL, 'Ricardo Santos', '1980-09-10', 'PRODUTOR', NULL),
(TRUE, '13420568000', NULL, 'Patrícia Gomes', '1987-01-22', 'PRODUTOR', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'ricardo.santos@email.com', 'ricardosantos', '$2a$10$senhaHash5', 5),
(NULL, NULL, CURRENT_TIMESTAMP, 'patricia.gomes@email.com', 'patriciagomes', '$2a$10$senhaHash6', 6);

-- TECNICO_SOM
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '42895137090', NULL, 'André Costa', '1991-05-14', 'TECNICO_SOM', NULL),
(TRUE, '89632541034', NULL, 'Luciana Pires', '1989-08-30', 'TECNICO_SOM', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'andre.costa@email.com', 'andrecosta', '$2a$10$senhaHash7', 7),
(NULL, NULL, CURRENT_TIMESTAMP, 'luciana.pires@email.com', 'lucianapires', '$2a$10$senhaHash8', 8);

-- TECNICO_LUZ
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '35914826075', NULL, 'Marcelo Oliveira', '1984-02-19', 'TECNICO_LUZ', NULL),
(TRUE, '61248593012', NULL, 'Tatiane Ribeiro', '1993-06-07', 'TECNICO_LUZ', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'marcelo.oliveira@email.com', 'marcelooliveira', '$2a$10$senhaHash9', 9),
(NULL, NULL, CURRENT_TIMESTAMP, 'tatiane.ribeiro@email.com', 'tatianeribeiro', '$2a$10$senhaHash10', 10);

-- TECNICO_MONITOR
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '92581436089', NULL, 'Rodrigo Mendes', '1986-09-21', 'TECNICO_MONITOR', NULL),
(TRUE, '25814963027', NULL, 'Aline Carvalho', '1994-12-11', 'TECNICO_MONITOR', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'rodrigo.mendes@email.com', 'rodrigomendes', '$2a$10$senhaHash11', 11),
(NULL, NULL, CURRENT_TIMESTAMP, 'aline.carvalho@email.com', 'alinecarvalho', '$2a$10$senhaHash12', 12);

-- TECNICO_PA
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '58149632041', NULL, 'Felipe Duarte', '1983-03-05', 'TECNICO_PA', NULL),
(TRUE, '89432051068', NULL, 'Carolina Nunes', '1995-08-17', 'TECNICO_PA', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'felipe.duarte@email.com', 'felipeduarte', '$2a$10$senhaHash13', 13),
(NULL, NULL, CURRENT_TIMESTAMP, 'carolina.nunes@email.com', 'carolinanunes', '$2a$10$senhaHash14', 14);

-- ROAD
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '14958236096', NULL, 'Daniel Moreira', '1982-04-22', 'ROAD', NULL),
(TRUE, '49582361053', NULL, 'Renata Rodrigues', '1996-10-09', 'ROAD', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'daniel.moreira@email.com', 'danielmoreira', '$2a$10$senhaHash15', 15),
(NULL, NULL, CURRENT_TIMESTAMP, 'renata.rodrigues@email.com', 'renatarodrigues', '$2a$10$senhaHash16', 16);

-- ARTISTA
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '72361958000', NULL, 'Gustavo Barros', '1987-06-13', 'ARTISTA', NULL),
(TRUE, '06195823028', NULL, 'Natália Teixeira', '1992-11-27', 'ARTISTA', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'gustavo.barros@email.com', 'gustavobarros', '$2a$10$senhaHash17', 17),
(NULL, NULL, CURRENT_TIMESTAMP, 'natalia.teixeira@email.com', 'nataliateixeira', '$2a$10$senhaHash18', 18);

-- GUITARRISTA
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '39582164085', NULL, 'Paulo Guitarra', '1985-04-10', 'GUITARRISTA', NULL),
(TRUE, '64219583019', NULL, 'Marina Guitarra', '1990-09-21', 'GUITARRISTA', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'paulo.guitarra@email.com', 'pauloguitarra', '$2a$10$senhaHash19', 19),
(NULL, NULL, CURRENT_TIMESTAMP, 'marina.guitarra@email.com', 'marinaguitarra', '$2a$10$senhaHash20', 20);

-- BAIXISTA
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '95832164076', NULL, 'Roberto Baixo', '1982-02-14', 'BAIXISTA', NULL),
(TRUE, '21649583030', NULL, 'Juliana Baixo', '1993-07-30', 'BAIXISTA', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'roberto.baixo@email.com', 'robertobaixo', '$2a$10$senhaHash21', 21),
(NULL, NULL, CURRENT_TIMESTAMP, 'juliana.baixo@email.com', 'julianabaixo', '$2a$10$senhaHash22', 22);

-- BATERISTA
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '58321649057', NULL, 'Thiago Batera', '1987-05-19', 'BATERISTA', NULL),
(TRUE, '83216495090', NULL, 'Camila Batera', '1991-11-03', 'BATERISTA', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'thiago.batera@email.com', 'thiagobatera', '$2a$10$senhaHash23', 23),
(NULL, NULL, CURRENT_TIMESTAMP, 'camila.batera@email.com', 'camilabatera', '$2a$10$senhaHash24', 24);

-- TECLADISTA
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '16495832046', NULL, 'Eduardo Teclado', '1984-08-12', 'TECLADISTA', NULL),
(TRUE, '49583216003', NULL, 'Larissa Teclado', '1992-01-27', 'TECLADISTA', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'eduardo.teclado@email.com', 'eduardoteclado', '$2a$10$senhaHash25', 25),
(NULL, NULL, CURRENT_TIMESTAMP, 'larissa.teclado@email.com', 'larissateclado', '$2a$10$senhaHash26', 26);

-- VIOLONISTA
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '73216495060', NULL, 'Marcelo Violão', '1986-06-15', 'VIOLONISTA', NULL),
(TRUE, '04958321087', NULL, 'Tatiane Violão', '1994-03-08', 'VIOLONISTA', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'marcelo.viola@email.com', 'marceloviola', '$2a$10$senhaHash27', 27),
(NULL, NULL, CURRENT_TIMESTAMP, 'tatiane.viola@email.com', 'tatianeviola', '$2a$10$senhaHash28', 28);

-- VOCALISTA
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '32164958014', NULL, 'Felipe Vocal', '1986-02-15', 'VOCALISTA', NULL),
(TRUE, '64958321071', NULL, 'Carla Vocal', '1991-09-28', 'VOCALISTA', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'felipe.vocal@email.com', 'felipevocal', '$2a$10$senhaHash29', 29),
(NULL, NULL, CURRENT_TIMESTAMP, 'carla.vocal@email.com', 'carlavocal', '$2a$10$senhaHash30', 30);

-- SAXOFONISTA
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '95832164025', NULL, 'Rafael Sax', '1984-07-12', 'SAXOFONISTA', NULL),
(TRUE, '21649583081', NULL, 'Juliana Sax', '1993-03-05', 'SAXOFONISTA', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'rafael.sax@email.com', 'rafaelsax', '$2a$10$senhaHash31', 31),
(NULL, NULL, CURRENT_TIMESTAMP, 'juliana.sax@email.com', 'julianasax', '$2a$10$senhaHash32', 32);

-- TROMPETISTA
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '58321649006', NULL, 'Bruno Trompete', '1982-11-20', 'TROMPETISTA', NULL),
(TRUE, '83216495030', NULL, 'Tatiane Trompete', '1990-04-14', 'TROMPETISTA', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'bruno.trompete@email.com', 'brunotrompete', '$2a$10$senhaHash33', 33),
(NULL, NULL, CURRENT_TIMESTAMP, 'tatiane.trompete@email.com', 'tatianetrompete', '$2a$10$senhaHash34', 34);

-- TROMBONISTA
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '16495832097', NULL, 'Marcelo Trombone', '1985-06-09', 'TROMBONISTA', NULL),
(TRUE, '49583216054', NULL, 'Renata Trombone', '1992-12-01', 'TROMBONISTA', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'marcelo.trombone@email.com', 'marcelotrombone', '$2a$10$senhaHash35', 35),
(NULL, NULL, CURRENT_TIMESTAMP, 'renata.trombone@email.com', 'renatatrombone', '$2a$10$senhaHash36', 36);

-- PERCUSSIONISTA
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '73216495010', NULL, 'Diego Percussão', '1987-08-17', 'PERCUSSIONISTA', NULL),
(TRUE, '04958321036', NULL, 'Vanessa Percussão', '1994-02-22', 'PERCUSSIONISTA', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'diego.percussao@email.com', 'diegopercussao', '$2a$10$senhaHash37', 37),
(NULL, NULL, CURRENT_TIMESTAMP, 'vanessa.percussao@email.com', 'vanessapercussao', '$2a$10$senhaHash38', 38);

-- VIOLINISTA
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '32164958065', NULL, 'Hugo Violino', '1983-01-11', 'VIOLINISTA', NULL),
(TRUE, '64958321020', NULL, 'Juliana Violino', '1995-09-03', 'VIOLINISTA', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'hugo.violino@email.com', 'hugoviolino', '$2a$10$senhaHash39', 39),
(NULL, NULL, CURRENT_TIMESTAMP, 'juliana.violino@email.com', 'julianaviolino', '$2a$10$senhaHash40', 40);

-- CELISTA
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '95832164084', NULL, 'Leonardo Cello', '1984-03-22', 'CELISTA', NULL),
(TRUE, '21649583049', NULL, 'Mariana Cello', '1992-07-19', 'CELISTA', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'leonardo.cello@email.com', 'leonardocello', '$2a$10$senhaHash41', 41),
(NULL, NULL, CURRENT_TIMESTAMP, 'mariana.cello@email.com', 'marianacello', '$2a$10$senhaHash42', 42);

-- CONTRABAIXISTA
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '58321649065', NULL, 'Roberto Contrabaixo', '1981-05-11', 'CONTRABAIXISTA', NULL),
(TRUE, '83216495006', NULL, 'Tatiane Contrabaixo', '1993-09-25', 'CONTRABAIXISTA', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'roberto.contrabaixo@email.com', 'robertocontrabaixo', '$2a$10$senhaHash43', 43),
(NULL, NULL, CURRENT_TIMESTAMP, 'tatiane.contrabaixo@email.com', 'tatianecontrabaixo', '$2a$10$senhaHash44', 44);

-- FLAUTISTA
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '16495832003', NULL, 'Camila Flauta', '1987-08-14', 'FLAUTISTA', NULL),
(TRUE, '49583216062', NULL, 'Pedro Flauta', '1994-02-03', 'FLAUTISTA', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'camila.flauta@email.com', 'camilaflauta', '$2a$10$senhaHash45', 45),
(NULL, NULL, CURRENT_TIMESTAMP, 'pedro.flauta@email.com', 'pedroflauta', '$2a$10$senhaHash46', 46);

-- CLARINETISTA
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '73216495079', NULL, 'Daniel Clarinete', '1985-10-09', 'CLARINETISTA', NULL),
(TRUE, '04958321095', NULL, 'Larissa Clarinete', '1991-12-27', 'CLARINETISTA', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'daniel.clarinete@email.com', 'danielclarinete', '$2a$10$senhaHash47', 47),
(NULL, NULL, CURRENT_TIMESTAMP, 'larissa.clarinete@email.com', 'larissaclarinete', '$2a$10$senhaHash48', 48);

-- OBOISTA
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '32164958022', NULL, 'Marcelo Oboé', '1983-06-18', 'OBOISTA', NULL),
(TRUE, '64958321080', NULL, 'Renata Oboé', '1992-01-29', 'OBOISTA', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'marcelo.oboe@email.com', 'marcelooboe', '$2a$10$senhaHash49', 49),
(NULL, NULL, CURRENT_TIMESTAMP, 'renata.oboe@email.com', 'renataoboe', '$2a$10$senhaHash50', 50);

-- FAGOTISTA
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '95832164033', NULL, 'Hugo Fagote', '1986-04-07', 'FAGOTISTA', NULL),
(TRUE, '21649583090', NULL, 'Juliana Fagote', '1994-09-12', 'FAGOTISTA', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'hugo.fagote@email.com', 'hugofagote', '$2a$10$senhaHash51', 51),
(NULL, NULL, CURRENT_TIMESTAMP, 'juliana.fagote@email.com', 'julianafagote', '$2a$10$senhaHash52', 52);

-- HARPISTA
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '58321649014', NULL, 'Beatriz Harpa', '1988-11-23', 'HARPISTA', NULL),
(TRUE, '83216495049', NULL, 'Lucas Harpa', '1995-05-16', 'HARPISTA', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'beatriz.harpa@email.com', 'beatrizharpa', '$2a$10$senhaHash53', 53),
(NULL, NULL, CURRENT_TIMESTAMP, 'lucas.harpa@email.com', 'lucasharpa', '$2a$10$senhaHash54', 54);

-- PIANISTA
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '16495832054', NULL, 'Eduardo Piano', '1982-02-20', 'PIANISTA', NULL),
(TRUE, '49583216011', NULL, 'Larissa Piano', '1990-07-08', 'PIANISTA', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'eduardo.piano@email.com', 'eduardopiano', '$2a$10$senhaHash55', 55),
(NULL, NULL, CURRENT_TIMESTAMP, 'larissa.piano@email.com', 'larissapiano', '$2a$10$senhaHash56', 56);

-- ACORDEONISTA
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '73216495028', NULL, 'Mateus Acordeon', '1985-05-10', 'ACORDEONISTA', NULL),
(TRUE, '04958321044', NULL, 'Carla Acordeon', '1992-09-18', 'ACORDEONISTA', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'mateus.acordeon@email.com', 'mateusacordeon', '$2a$10$senhaHash57', 57),
(NULL, NULL, CURRENT_TIMESTAMP, 'carla.acordeon@email.com', 'carlaacordeon', '$2a$10$senhaHash58', 58);

-- GAITEIRO
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '32164958073', NULL, 'Rafael Gaita', '1983-07-12', 'GAITEIRO', NULL),
(TRUE, '64958321038', NULL, 'Juliana Gaita', '1994-03-05', 'GAITEIRO', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'rafael.gaita@email.com', 'rafaelgaita', '$2a$10$senhaHash59', 59),
(NULL, NULL, CURRENT_TIMESTAMP, 'juliana.gaita@email.com', 'julianagaita', '$2a$10$senhaHash60', 60);

-- BANDOLINISTA
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '95832164092', NULL, 'Bruno Bandolim', '1982-11-20', 'BANDOLINISTA', NULL),
(TRUE, '21649583057', NULL, 'Tatiane Bandolim', '1990-04-14', 'BANDOLINISTA', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'bruno.bandolim@email.com', 'brunobandolim', '$2a$10$senhaHash61', 61),
(NULL, NULL, CURRENT_TIMESTAMP, 'tatiane.bandolim@email.com', 'tatianebandolim', '$2a$10$senhaHash62', 62);

-- CAVAQUINISTA
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '58321649073', NULL, 'Marcelo Cavaquinho', '1985-06-09', 'CAVAQUINISTA', NULL),
(TRUE, '83216495014', NULL, 'Renata Cavaquinho', '1992-12-01', 'CAVAQUINISTA', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'marcelo.cavaquinho@email.com', 'marcelocavaquinho', '$2a$10$senhaHash63', 63),
(NULL, NULL, CURRENT_TIMESTAMP, 'renata.cavaquinho@email.com', 'renatacavaquinho', '$2a$10$senhaHash64', 64);

-- UKULELISTA
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '16495832011', NULL, 'Diego Ukulele', '1987-08-17', 'UKULELISTA', NULL),
(TRUE, '49583216070', NULL, 'Vanessa Ukulele', '1994-02-22', 'UKULELISTA', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'diego.ukulele@email.com', 'diegoukulele', '$2a$10$senhaHash65', 65),
(NULL, NULL, CURRENT_TIMESTAMP, 'vanessa.ukulele@email.com', 'vanessaukulele', '$2a$10$senhaHash66', 66);

-- GUITARRA_RITMICA
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '73216495087', NULL, 'Paulo Base', '1985-05-10', 'GUITARRA_RITMICA', NULL),
(TRUE, '04958321001', NULL, 'Carla Base', '1992-09-18', 'GUITARRA_RITMICA', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'paulo.base@email.com', 'paulobase', '$2a$10$senhaHash67', 67),
(NULL, NULL, CURRENT_TIMESTAMP, 'carla.base@email.com', 'carlabase', '$2a$10$senhaHash68', 68);

-- GUITARRA_SOLO
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '32164958030', NULL, 'Rafael Solo', '1983-07-12', 'GUITARRA_SOLO', NULL),
(TRUE, '64958321098', NULL, 'Juliana Solo', '1994-03-05', 'GUITARRA_SOLO', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'rafael.solo@email.com', 'rafaelsolo', '$2a$10$senhaHash69', 69),
(NULL, NULL, CURRENT_TIMESTAMP, 'juliana.solo@email.com', 'julianasolo', '$2a$10$senhaHash70', 70);

-- DJ
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '95832164041', NULL, 'Bruno DJ', '1982-11-20', 'DJ', NULL),
(TRUE, '21649583006', NULL, 'Tatiane DJ', '1990-04-14', 'DJ', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'bruno.dj@email.com', 'brunodj', '$2a$10$senhaHash71', 71),
(NULL, NULL, CURRENT_TIMESTAMP, 'tatiane.dj@email.com', 'tatianedj', '$2a$10$senhaHash72', 72);

-- MC
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '58321649022', NULL, 'Marcelo MC', '1985-06-09', 'MC', NULL),
(TRUE, '83216495057', NULL, 'Renata MC', '1992-12-01', 'MC', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'marcelo.mc@email.com', 'marcelomc', '$2a$10$senhaHash73', 73),
(NULL, NULL, CURRENT_TIMESTAMP, 'renata.mc@email.com', 'renatamc', '$2a$10$senhaHash74', 74);

-- MAESTRO
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '16495832062', NULL, 'Diego Maestro', '1987-08-17', 'MAESTRO', NULL),
(TRUE, '49583216020', NULL, 'Vanessa Maestro', '1994-02-22', 'MAESTRO', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'diego.maestro@email.com', 'diegomaestro', '$2a$10$senhaHash75', 75),
(NULL, NULL, CURRENT_TIMESTAMP, 'vanessa.maestro@email.com', 'vanessamaestro', '$2a$10$senhaHash76', 76);

-- REGENTE
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '73216495037', NULL, 'Paulo Regente', '1985-05-10', 'REGENTE', NULL),
(TRUE, '04958321052', NULL, 'Carla Regente', '1992-09-18', 'REGENTE', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'paulo.regente@email.com', 'pauloregente', '$2a$10$senhaHash77', 77),
(NULL, NULL, CURRENT_TIMESTAMP, 'carla.regente@email.com', 'carlaregente', '$2a$10$senhaHash78', 78);

-- COMPOSITOR
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '32164958081', NULL, 'Rafael Compositor', '1983-07-12', 'COMPOSITOR', NULL),
(TRUE, '64958321046', NULL, 'Juliana Compositor', '1994-03-05', 'COMPOSITOR', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'rafael.compositor@email.com', 'rafaelcompositor', '$2a$10$senhaHash79', 79),
(NULL, NULL, CURRENT_TIMESTAMP, 'juliana.compositor@email.com', 'julianacompositor', '$2a$10$senhaHash80', 80);

-- ARRANJADOR
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '95832164009', NULL, 'Bruno Arranjo', '1982-11-20', 'ARRANJADOR', NULL),
(TRUE, '21649583065', NULL, 'Tatiane Arranjo', '1990-04-14', 'ARRANJADOR', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'bruno.arranjo@email.com', 'brunoarranjo', '$2a$10$senhaHash81', 81),
(NULL, NULL, CURRENT_TIMESTAMP, 'tatiane.arranjo@email.com', 'tatianearranjo', '$2a$10$senhaHash82', 82);

-- PRODUTOR_MUSICAL
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '58321649081', NULL, 'Marcelo Produtor Musical', '1985-06-09', 'PRODUTOR_MUSICAL', NULL),
(TRUE, '83216495022', NULL, 'Renata Produtor Musical', '1992-12-01', 'PRODUTOR_MUSICAL', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'marcelo.produtor@email.com', 'marceloprodutor', '$2a$10$senhaHash83', 83),
(NULL, NULL, CURRENT_TIMESTAMP, 'renata.produtor@email.com', 'renataprodutor', '$2a$10$senhaHash84', 84);

-- ENGENHEIRO_SOM
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '16495832020', NULL, 'Diego Engenheiro Som', '1987-08-17', 'ENGENHEIRO_SOM', NULL),
(TRUE, '49583216089', NULL, 'Vanessa Engenheira Som', '1994-02-22', 'ENGENHEIRO_SOM', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'diego.engenheiro@email.com', 'diegoengenheiro', '$2a$10$senhaHash85', 85),
(NULL, NULL, CURRENT_TIMESTAMP, 'vanessa.engenheira@email.com', 'vanessaengenheira', '$2a$10$senhaHash86', 86);

-- LETRISTA
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '73216495096', NULL, 'Hugo Letrista', '1983-01-11', 'LETRISTA', NULL),
(TRUE, '04958321010', NULL, 'Juliana Letrista', '1995-09-03', 'LETRISTA', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'hugo.letrista@email.com', 'hugoletrista', '$2a$10$senhaHash87', 87),
(NULL, NULL, CURRENT_TIMESTAMP, 'juliana.letrista@email.com', 'julianaletrista', '$2a$10$senhaHash88', 88);

-- BACKING_VOCAL
INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '32164958049', NULL, 'Felipe Arranjo Vocal', '1986-02-15', 'BACKING_VOCAL', NULL);

INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, CURRENT_TIMESTAMP, 'felipe.arranjo@email.com', 'felipearranjo', '$2a$10$senhaHash89', 89);


INSERT INTO COLABORADOR_ENTITY (ATIVO, CPF, FOTO_NOME, NOME, DATA_NASCIMENTO, TIPO_USUARIO, ENDERECO_ID) VALUES
(TRUE, '47060193898', NULL, 'Gabriel Sousa', '2000-05-15', 'PRODUTOR', NULL);


INSERT INTO CREDENCIAIS_USUARIO_ENTITY (CODIGO_EXPIRA_EM, CODIGO_RECUPERACAO, DATA_HORA_ULTIMO_ACESSO, EMAIL, NOME_USUARIO, SENHA, USUARIO_ID) VALUES
(NULL, NULL, '2025-12-01 11:46:16.782137', 'gabriel.sousa@example.com', 'gabrielsousa', '$2a$10$G.klFRRb/ilL2dBBTpw4..o3D0sGN0qppM.fsNLADhgcd82jnRwTi', 90);